# Folder where we want to store all the output files
# WARNING: Currently only "" was tested
out_folder: ""
# File ending of the MAGS
mag_ending: ".fna"
# Folder of the MAGs. All the MAGs should end in `mag_ending`
input_folder: "tutorial_files/"
# Currently unused due to the fact the we do use the predicted media
medium: "tutorial_files/gf_medium.csv"
# Use the above specified medium or not not. Can be set to "true" or "false"
use_medium: "true"
