cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --qos={resources.qos}
    --cpus-per-task={resources.threads}
    --mem={resources.mem_mb}
    --time={resources.time}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --error=logs/{rule}/{rule}-{wildcards}-%j.err
    --parsable
default-resources:
  - qos=normal
  - mem_mb=1000
  - time="2:00:00"
  - threads=1
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
cluster-status: status-script.sh
